### ISSUE TITLE
可以基于OpenCV推理特征网络吗？

### ISSUE THREAD

**Issue by a243845305** [shaoshengsong/DeepSORT#2]
我尝试使用OpenCV的dnn模块读取mars-small128.pb模型，其中mars-small128.pbtxt文件是根据mars-small128.pb转换得到的。
遇到了错误：Unknown enumeration value of "DT_RESOURCE" for field "type".
1.是我在生成pbtxt的方式不对吗？如果是的话，请问该如何根据模型文件生成pbtxt文件呢？
2.Up主有尝试将mars-small128.pb模型用dnn读取吗？可以的话整个项目就无需依赖TensorFlow环境了。

**Comment by lightsalt2011** [comment]
> 我尝试使用OpenCV的dnn模块读取mars-small128.pb模型，其中mars-small128.pbtxt文件是根据mars-small128.pb转换得到的。
> 遇到了错误：Unknown enumeration value of "DT_RESOURCE" for field "type".
> 1.是我在生成pbtxt的方式不对吗？如果是的话，请问该如何根据模型文件生成pbtxt文件呢？
> 2.Up主有尝试将mars-small128.pb模型用dnn读取吗？可以的话整个项目就无需依赖TensorFlow环境了。

请问使用OpenCV的dnn模块读取mars-small128.pb模型验证成功了吗

**Comment by Challovactor** [comment]
同问，感谢！

**Comment by a243845305** [comment]
> > 我尝试使用OpenCV的dnn模块读取mars-small128.pb模型，其中mars-small128.pbtxt文件是根据mars-small128.pb转换得到的。
> > 遇到了错误：Unknown enumeration value of "DT_RESOURCE" for field "type".
> > 1.是我在生成pbtxt的方式不对吗？如果是的话，请问该如何根据模型文件生成pbtxt文件呢？
> > 2.Up主有尝试将mars-small128.pb模型用dnn读取吗？可以的话整个项目就无需依赖TensorFlow环境了。
> 
> 请问使用OpenCV的dnn模块读取mars-small128.pb模型验证成功了吗

没有额。

**Comment by huichengchen** [comment]
> 我尝试使用OpenCV的dnn模块读取mars-small128.pb模型，其中mars-small128.pbtxt文件是根据mars-small128.pb转换得到的。
> 遇到了错误：Unknown enumeration value of "DT_RESOURCE" for field "type".
> 1.是我在生成pbtxt的方式不对吗？如果是的话，请问该如何根据模型文件生成pbtxt文件呢？
> 2.Up主有尝试将mars-small128.pb模型用dnn读取吗？可以的话整个项目就无需依赖TensorFlow环境了。

我重新训练了网络，可以使用opencv加载，模型文件链接: https://pan.baidu.com/s/1Nve6hcABCLBgYquVWVDkzw 提取码: qnjv

**Comment by jueyisan** [comment]
> > 我尝试使用OpenCV的dnn模块读取mars-small128.pb模型，其中mars-small128.pbtxt文件是根据mars-small128.pb转换得到的。
> > 遇到了错误：Unknown enumeration value of "DT_RESOURCE" for field "type".
> > 1.是我在生成pbtxt的方式不对吗？如果是的话，请问该如何根据模型文件生成pbtxt文件呢？
> > 2.Up主有尝试将mars-small128.pb模型用dnn读取吗？可以的话整个项目就无需依赖TensorFlow环境了。
> 
> 我重新训练了网络，可以使用opencv加载，模型文件链接: https://pan.baidu.com/s/1Nve6hcABCLBgYquVWVDkzw 提取码: qnjv

修改以后的代码要怎么写呢？能不能提供一下源码
