### ISSUE TITLE
模型转换相关问题

### ISSUE THREAD

**Issue by captain0305** [shaoshengsong/DeepSORT#26]
我的模型转换后会有报错
![image](https://user-images.githubusercontent.com/63387697/194698520-1091a90b-e99a-4277-a568-d9721cf8ad57.png)
是否是我的模型转换有问题？
我使用自己yolov5m模型的yolov5版本为v6.1

**Comment by shaoshengsong** [comment]
可以先使用最新版6.2 试试
输入节点，name：images
shape NCHW=[1,3,640,640]
输出节点，name: output
shape [1,25200,85]
